### ISSUE TITLE
click item will be crashed , when make listview  add footer view

### ISSUE THREAD

**Issue by ghost** [Yalantis/FlipViewPager.Draco#10]
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.IndexOutOfBoundsException: Invalid index 9, size is 1
                                                                                   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)

**Comment by TeeRawk** [comment]
Hello, i found the problem. 
 friends.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                   if(position<friends.getAdapter().getCount()){
                Friend f = (Friend) friends.getAdapter().getItem(position);
                Toast.makeText(FriendsActivity.this, f.getNickname(), Toast.LENGTH_SHORT).show();
}
            }
        });

because by adding the footer you add more item to the listView , but not to the list itself,so you will need the protecting if.
