### ISSUE TITLE
Right Image can flip 10 times

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Yalantis/FlipViewPager.Draco#11]
Hi! I copied all the code from the sample and the images on the right side can flip 10 times, why is it happening? shouldn't it flip just one time?
Also, when here is an odd number of items, the very last space (which holds no item, cause it's an odd number) can be flipped
Thanks!

**Comment by TeeRawk** [comment]
Hello,sorry but we can't reproduce this

**Comment by TeeRawk** [comment]
Outdated
