### ISSUE TITLE
Sample with errors

### ISSUE THREAD

**Issue by curliq** [Yalantis/FlipViewPager.Draco#15]
Hi, I'm trying to implement this beautiful library in my project, what is happening is I cannot set an adapter that extends BaseFlipAdapter in a ListView. In the sample the ListView friends sets a BaseFlipAdapter and for some reason it can't, help please.

**Comment by yasbf** [comment]
Same issue for me.
What should I do to fix this problem ?

**Comment by curliq** [comment]
@ahmediego Still looking for it, have you fixed it?

@cleanOK Any thoughts?

**Comment by yasbf** [comment]
@joaosardinha Same for me, still looking for it.

**Comment by gjohnrao** [comment]
may be it doesn't work with api 23, if anyone found some solution , kindly post it in here

**Comment by curliq** [comment]
@johnrao7 I doubt that's that problem

![image](https://cloud.githubusercontent.com/assets/15181917/14150695/32d17baa-f6a2-11e5-8030-a9c6f7660510.png)

**Comment by gjohnrao** [comment]
@joaosardinha maybe it stopped working since then

**Comment by akrupych-remit** [comment]
dev branch has working sample

**Comment by curliq** [comment]
@akrupych-remit can you link it here?

**Comment by akrupych-remit** [comment]
Sure I can: https://github.com/Yalantis/FlipViewPager.Draco/tree/develop

**Comment by curliq** [comment]
@johnrao7 @ahmediego I just updated Android Studio to v2 and the sample is working
