### ISSUE TITLE
about item click

### ISSUE THREAD

**Issue by weity** [Yalantis/FlipViewPager.Draco#18]
It's not proper about code if(ev.getRowX() == mLastMotionX || ev.getRowY() == mLastMotionY)  in FlipViewPager to judge wether user click or not.

I change the code like below:
  if (Math.abs(ev.getX() - mLastMotionX) < mTouchSlop ||
                            Math.abs(ev.getY() - mLastMotionY) < mTouchSlop) 
and it works fine.

**Comment by dingbuoyi** [comment]
Thank you very much , man ! It works perfect!

**Comment by warko-san** [comment]
Hi, @weity! Thank you for your solution. You can suggest pull request to fix this issue. We appreciate it.

**Comment by TeeRawk** [comment]
resolved
