### ISSUE TITLE
friends(Listview) can't be set adapter with FriendsAdapter

### ISSUE THREAD

**Issue by ghost** [Yalantis/FlipViewPager.Draco#19]
I want to start sample java file But It can't be start Because It can't be set adapter with FriendsAdapter... why can't I do that?

**Comment by TeeRawk** [comment]
Hello, @myeongsic89  , can you please provide some code ?

**Comment by myeongsic89** [comment]
I'm sorry I'm late, I found the solution https://github.com/Yalantis/FlipViewPager.Draco/issues/17

**Comment by ghost** [comment]
sorry I'm late I found the solution https://github.com/Yalantis/FlipViewPager.Draco/issues/17
