### ISSUE TITLE
listview set a wrong adaptor

### ISSUE THREAD

**Issue by luoguibin** [Yalantis/FlipViewPager.Draco#20]
Java code(FriendsActivity):
friends.setAdapter(new FriendsAdapter(this, Utils.friends, settings));

Here are the errors:
Error:(36, 16) error: no suitable method found for setAdapter(FriendsActivity.FriendsAdapter)
method AdapterView.setAdapter(ListAdapter) is not applicable
(argument mismatch; FriendsActivity.FriendsAdapter cannot be converted to ListAdapter)
method AbsListView.setAdapter(ListAdapter) is not applicable
(argument mismatch; FriendsActivity.FriendsAdapter cannot be converted to ListAdapter)
method ListView.setAdapter(ListAdapter) is not applicable
(argument mismatch; FriendsActivity.FriendsAdapter cannot be converted to ListAdapter)

**Comment by TeeRawk** [comment]
Hi, @luoguibin , can you provide some more code. Specifically i want to look at your FriendsAdapter

**Comment by Ujjawal-Anand** [comment]
Having the same issue. I just wanted to try the sample before implementing it in my own project. It's giving me the above mentioned error by @luoguibin

**Comment by warko-san** [comment]
Hi, @andy1729! Are you using `ListView` or `RecyclerView`?

**Comment by Ujjawal-Anand** [comment]
Hello, @warko-san sorry for late reply, I am using ListView. Should I use RecyclerView?

**Comment by val-raman** [comment]
I am also facing the same problem. List view adapter showing error

**Comment by ghost** [comment]
is there anyway to use recyclerAdapter?

**Comment by luoguibin** [comment]
Say goodbye to Android, say hello to H5~
