### ISSUE TITLE
used inside viewpager

### ISSUE THREAD

**Issue by MikhilPastagia** [Yalantis/FlipViewPager.Draco#3]
i want to use FlipViewPager inside viewpager, it is not worked.. because when i flip it considered its parent view.. in my side, i am using as parent view, viewpager... so how to implement it inside viewpager...

**Comment by MikhilPastagia** [comment]
Please answer me...

**Comment by TheBlusky** [comment]
Same issue here.
As a workaround, I used this:
http://stackoverflow.com/questions/9650265/how-do-disable-paging-by-swiping-with-finger-in-viewpager-but-still-be-able-to-s
