### ISSUE TITLE
OnItemClick works only with two fingers or repeated clicks

### ISSUE THREAD

**Issue by jimmy25** [Yalantis/FlipViewPager.Draco#4]
There will be a fix for this problem? thank you

**Comment by Aenterhy** [comment]
What is the OS version are you using? 
Can't reproduce for now :-(

**Comment by jimmy25** [comment]
Android 5.02 , thanks for replying

**Comment by TeeRawk** [comment]
Cannot reproduce

**Comment by arhamranjha** [comment]
I am having the same issue any solution to it ?
