### ISSUE TITLE
Is it possible to programmatically open a detailled view ?

### ISSUE THREAD

**Issue by TheBlusky** [Yalantis/FlipViewPager.Draco#6]
I think everything is on the subject :-)

It's in the case a user click on a picture, so the detailed view is opened.

I think it's not natural to swipe the view if you don't know already what is behind.

**Comment by ilkea** [comment]
This is possible. But you should add code your project and you can customize the code. For example I put a close button in detail view. And when I clicked the close button, the view return to first page.

**Comment by rockingnishant** [comment]
Hi ,
Can you explain the way or give code snippet to achieve this.Thanks in advance

**Comment by Syex** [comment]
Closing is possible via FlipViewPager.flipToPage(DEFAULT_PAGE)
