### ISSUE TITLE
Row Height on Tablet

### ISSUE THREAD

**Issue by erahal** [Yalantis/FlipViewPager.Draco#9]
Hello,

Thank you for the library, I am using it in a project but when I test it on a tablet, the row height is too narrow. And the images appears with a very wrong aspect ratio. I tried changing the scale type but nothing worked. The problem seems in the listView row height. ( The problem also is present in the demo provided with your pictures)

Do you have any idea how to change the row height? 

Thank you
Elie

**Comment by TeeRawk** [comment]
Hello, thanks for your feedback,we're working to fix that. When repository updates there will be method setItemHeight in BaseFlipAdapter, so you can call it in getPage like this setItemHeight(getResources().getDimension(R.dimen.item_height));. 
Alse you will need to override dimension for different screeens ,and set this height for image views in your merge_page.xml .Like this 
    <ImageView
        android:id="@+id/first"
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="0dp"
        android:layout_weight="1"
        android:contentDescription="left image"
        android:layout_height="@dimen/item_height"
        android:scaleType="fitXY" />

```
<LinearLayout
    android:layout_width="1dp"
    android:layout_weight="0"
    android:background="#000000"
    android:layout_height="@dimen/item_height"/>

<ImageView
    android:id="@+id/second"
    android:layout_width="0dp"
    android:layout_weight="1"
    android:contentDescription="right image"
    android:layout_height="@dimen/item_height"
    android:scaleType="fitXY" />
```

for example this dimens worked for me 

default dimens.xml

<dimen name="item_height">200dp</dimen>

dimens.xml (xlarge)

 <dimen name="item_height">400dp</dimen>

**Comment by erahal** [comment]
Thank you for the fix
